Lesson9 solution
Ognessa/Internship_Homework_1 pull request #9
Opened 2022-07-28 13:01 UTC by Ognessa

2022-07-29 12:21 UTC, shadwork requested changes
неплохо - но мало

2022-07-29 12:21 UTC, shadwork commented on app/src/main/java/com/onix/internship/objects/DataStore.kt
> +            deleteKey()
no needed in key deletion - one table - so - no relation between tables

2022-07-29 12:21 UTC, shadwork commented on app/src/main/java/com/onix/internship/objects/NotesColors.kt
> +        NotesColors.PINK -> Color.argb(255, 254, 79, 172)
colors should be in xml values

2022-07-29 12:21 UTC, shadwork commented on app/src/main/java/com/onix/internship/ui/addNote/AddNoteFragment.kt
> +    private fun createColorMenu(llColorsListContainer: LinearLayout) {
good but rewrite it with recycleview

2022-07-29 12:21 UTC, shadwork commented on app/src/main/java/com/onix/internship/ui/addNote/AddNoteViewModel.kt
> +    private val _note = MutableLiveData<NotesData>()
thinking about incapsulate all this staff into model with observable fields

2022-07-29 22:53 UTC, Ognessa commented on app/src/main/java/com/onix/internship/objects/DataStore.kt
> +            deleteKey()
Done

2022-07-29 22:53 UTC, Ognessa commented on app/src/main/java/com/onix/internship/objects/NotesColors.kt
> +        NotesColors.PINK -> Color.argb(255, 254, 79, 172)
Done

2022-07-30 03:53 UTC, shadwork approved these changes

2022-08-01 08:50 UTC, merged